/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.src;
import Giles.util.NewProcessor;
import Main.Main;

import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.io.IOException;

/**
 *
 * @author super
 */
public class Settings extends javax.swing.JFrame {


    /**
     * Creates new form Settings
     */
    public Settings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basisGroup = new javax.swing.ButtonGroup();
        regressionGroup = new javax.swing.ButtonGroup();
        namesGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        settingsTitle = new javax.swing.JLabel();
        networkSection = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        outputsFilebox = new javax.swing.JTextField();
        outputsChooseButton = new javax.swing.JButton();
        outputsOpenButton = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        inputsFilebox = new javax.swing.JTextField();
        inputsChooseButton = new javax.swing.JButton();
        inputsOpenButton = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        outputNamesFilebox = new javax.swing.JTextField();
        outputNamesChooseButton = new javax.swing.JButton();
        outputNamesOpenButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        saveReportFilebox = new javax.swing.JTextField();
        saveReportChooseButton = new javax.swing.JButton();
        saveReportOpenButton = new javax.swing.JButton();
        saveReportCheckbox = new javax.swing.JCheckBox();
        jPanel22 = new javax.swing.JPanel();
        saveNetworkFilebox = new javax.swing.JTextField();
        saveNetworkChooseButton = new javax.swing.JButton();
        saveNetworkOpenButton = new javax.swing.JButton();
        saveNetworkCheckbox = new javax.swing.JCheckBox();
        jPanel23 = new javax.swing.JPanel();
        loadNetworkFilebox = new javax.swing.JTextField();
        loadNetworkChooseButton = new javax.swing.JButton();
        loadNetworkOpenButton = new javax.swing.JButton();
        loadNetworkCheckbox = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        imageCheckbox = new javax.swing.JCheckBox();
        printMonitorCheckbox = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        iterationsTextbox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        hiddenNeuronsTextbox = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        quadraticRadio = new javax.swing.JRadioButton();
        linearRadio = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        iterationRadio = new javax.swing.JRadioButton();
        accuracyRadio = new javax.swing.JRadioButton();
        dynamicRateCheckbox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        learningRateTextbox = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lettersNameTypeRadio = new javax.swing.JRadioButton();
        numbersNameTypeRadio = new javax.swing.JRadioButton();
        customTypeRadio = new javax.swing.JRadioButton();
        startButton = new javax.swing.JButton();
        backButton = new javax.swing.JToggleButton();
        exitButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        settingsTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        settingsTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        settingsTitle.setText("Settings");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(settingsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(settingsTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("*Expected Outputs File:");

        outputsFilebox.setText("Please Select a CSV File");
        outputsFilebox.setPreferredSize(new java.awt.Dimension(285, 20));
        outputsFilebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputsFileboxActionPerformed(evt);
            }
        });

        outputsChooseButton.setText("Choose");
        outputsChooseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputsChooseButtonActionPerformed(evt);
            }
        });

        outputsOpenButton.setText("Open");
        outputsOpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputsOpenButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(outputsFilebox, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputsChooseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(outputsOpenButton)
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(outputsFilebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(outputsChooseButton)
                .addComponent(outputsOpenButton))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("*Input Values File:");

        inputsFilebox.setText("Please Select a CSV File");
        inputsFilebox.setToolTipText("Please Select a CSV File");
        inputsFilebox.setPreferredSize(new java.awt.Dimension(285, 20));
        inputsFilebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputsFileboxActionPerformed(evt);
            }
        });

        inputsChooseButton.setText("Choose");
        inputsChooseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputsChooseButtonActionPerformed(evt);
            }
        });

        inputsOpenButton.setText("Open");
        inputsOpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputsOpenButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inputsFilebox, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputsChooseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inputsOpenButton)
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(inputsFilebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(inputsChooseButton)
                .addComponent(inputsOpenButton))
        );

        outputNamesFilebox.setText("Please Select a CSV File");
        outputNamesFilebox.setEnabled(false);
        outputNamesFilebox.setPreferredSize(new java.awt.Dimension(285, 20));
        outputNamesFilebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputNamesFileboxActionPerformed(evt);
            }
        });

        outputNamesChooseButton.setText("Choose");
        outputNamesChooseButton.setEnabled(false);
        outputNamesChooseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputNamesChooseButtonActionPerformed(evt);
            }
        });

        outputNamesOpenButton.setText("Open");
        outputNamesOpenButton.setEnabled(false);
        outputNamesOpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputNamesOpenButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Custom Output Names:");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputNamesFilebox, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputNamesChooseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(outputNamesOpenButton)
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(outputNamesFilebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(outputNamesChooseButton)
                .addComponent(outputNamesOpenButton)
                .addComponent(jLabel7))
        );

        saveReportFilebox.setText("Please Select a CSV File");
        saveReportFilebox.setPreferredSize(new java.awt.Dimension(285, 20));
        saveReportFilebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveReportFileboxActionPerformed(evt);
            }
        });

        saveReportChooseButton.setText("Choose");
        saveReportChooseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveReportChooseButtonActionPerformed(evt);
            }
        });

        saveReportOpenButton.setText("Open");
        saveReportOpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveReportOpenButtonActionPerformed(evt);
            }
        });

        saveReportCheckbox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        saveReportCheckbox.setSelected(true);
        saveReportCheckbox.setText("Save Report:");
        saveReportCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveReportCheckboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addComponent(saveReportCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(saveReportFilebox, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveReportChooseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveReportOpenButton)
                .addContainerGap())
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(saveReportFilebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(saveReportChooseButton)
                .addComponent(saveReportOpenButton)
                .addComponent(saveReportCheckbox))
        );

        saveNetworkFilebox.setText("Please Select a CSV File");
        saveNetworkFilebox.setPreferredSize(new java.awt.Dimension(285, 20));
        saveNetworkFilebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveNetworkFileboxActionPerformed(evt);
            }
        });

        saveNetworkChooseButton.setText("Choose");
        saveNetworkChooseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveNetworkChooseButtonActionPerformed(evt);
            }
        });

        saveNetworkOpenButton.setText("Open");
        saveNetworkOpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveNetworkOpenButtonActionPerformed(evt);
            }
        });

        saveNetworkCheckbox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        saveNetworkCheckbox.setSelected(true);
        saveNetworkCheckbox.setText("Save Network State:");
        saveNetworkCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveNetworkCheckboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addComponent(saveNetworkCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveNetworkFilebox, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveNetworkChooseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveNetworkOpenButton)
                .addContainerGap())
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(saveNetworkFilebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(saveNetworkChooseButton)
                .addComponent(saveNetworkOpenButton)
                .addComponent(saveNetworkCheckbox))
        );

        loadNetworkFilebox.setText("Please Select a CSV File");
        loadNetworkFilebox.setPreferredSize(new java.awt.Dimension(285, 20));
        loadNetworkFilebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadNetworkFileboxActionPerformed(evt);
            }
        });

        loadNetworkChooseButton.setText("Choose");
        loadNetworkChooseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadNetworkChooseButtonActionPerformed(evt);
            }
        });

        loadNetworkOpenButton.setText("Open");
        loadNetworkOpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadNetworkOpenButtonActionPerformed(evt);
            }
        });

        loadNetworkCheckbox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        loadNetworkCheckbox.setSelected(true);
        loadNetworkCheckbox.setText("Load Network State:");
        loadNetworkCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadNetworkCheckboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addComponent(loadNetworkCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadNetworkFilebox, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadNetworkChooseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loadNetworkOpenButton)
                .addContainerGap())
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(loadNetworkFilebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(loadNetworkChooseButton)
                .addComponent(loadNetworkOpenButton)
                .addComponent(loadNetworkCheckbox))
        );

        imageCheckbox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        imageCheckbox.setText("Create Image of Neural Network");
        imageCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageCheckboxActionPerformed(evt);
            }
        });

        printMonitorCheckbox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        printMonitorCheckbox.setText("Print Monitor");
        printMonitorCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printMonitorCheckboxActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("*Number of Iterations:");

        iterationsTextbox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        iterationsTextbox.setText("100000");
        iterationsTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iterationsTextboxActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("*Number of Hidden Neurons:");

        hiddenNeuronsTextbox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hiddenNeuronsTextbox.setText("24");
        hiddenNeuronsTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hiddenNeuronsTextboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hiddenNeuronsTextbox))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(iterationsTextbox))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imageCheckbox)
                            .addComponent(printMonitorCheckbox))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hiddenNeuronsTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iterationsTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(printMonitorCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imageCheckbox)
                .addContainerGap())
        );

        regressionGroup.add(quadraticRadio);
        quadraticRadio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        quadraticRadio.setText("Quadratic");
        quadraticRadio.setEnabled(false);

        regressionGroup.add(linearRadio);
        linearRadio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        linearRadio.setSelected(true);
        linearRadio.setText("Linear");
        linearRadio.setEnabled(false);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quadraticRadio)
                    .addComponent(linearRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(linearRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quadraticRadio))
        );

        basisGroup.add(iterationRadio);
        iterationRadio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        iterationRadio.setSelected(true);
        iterationRadio.setText("Iteration-Based");
        iterationRadio.setEnabled(false);
        iterationRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iterationRadioActionPerformed(evt);
            }
        });

        basisGroup.add(accuracyRadio);
        accuracyRadio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        accuracyRadio.setText("Accuracy-Based");
        accuracyRadio.setEnabled(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(accuracyRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iterationRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iterationRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(accuracyRadio)
                .addContainerGap())
        );

        dynamicRateCheckbox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dynamicRateCheckbox1.setText("Use Dynamic Learning Rate");
        dynamicRateCheckbox1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        dynamicRateCheckbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dynamicRateCheckbox1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("*Initial Learning Rate:");

        learningRateTextbox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        learningRateTextbox.setText("0.40");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(dynamicRateCheckbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(learningRateTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(learningRateTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dynamicRateCheckbox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Output Name Type:");

        namesGroup.add(lettersNameTypeRadio);
        lettersNameTypeRadio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lettersNameTypeRadio.setSelected(true);
        lettersNameTypeRadio.setText("Letters");
        lettersNameTypeRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lettersNameTypeRadioActionPerformed(evt);
            }
        });

        namesGroup.add(numbersNameTypeRadio);
        numbersNameTypeRadio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        numbersNameTypeRadio.setText("Numbers");
        numbersNameTypeRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbersNameTypeRadioActionPerformed(evt);
            }
        });

        namesGroup.add(customTypeRadio);
        customTypeRadio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        customTypeRadio.setText("Custom");
        customTypeRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customTypeRadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numbersNameTypeRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lettersNameTypeRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customTypeRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lettersNameTypeRadio)
                .addGap(7, 7, 7)
                .addComponent(numbersNameTypeRadio)
                .addGap(7, 7, 7)
                .addComponent(customTypeRadio)
                .addContainerGap())
        );

        javax.swing.GroupLayout networkSectionLayout = new javax.swing.GroupLayout(networkSection);
        networkSection.setLayout(networkSectionLayout);
        networkSectionLayout.setHorizontalGroup(
            networkSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(networkSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(networkSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(networkSectionLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        networkSectionLayout.setVerticalGroup(
            networkSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(networkSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(networkSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        startButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        startButton.setText("Start Program");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 723, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(networkSection, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 240, Short.MAX_VALUE)
                        .addComponent(startButton)
                        .addGap(240, 240, 240)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(networkSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startButton)
                    .addComponent(backButton)
                    .addComponent(exitButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iterationRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iterationRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iterationRadioActionPerformed

    private void hiddenNeuronsTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hiddenNeuronsTextboxActionPerformed
        if(!NewProcessor.isInteger(hiddenNeuronsTextbox.getText())){
            JOptionPane.showMessageDialog(null, "Number of hidden neurons must be an integer.", "Error", JOptionPane.ERROR_MESSAGE);
            hiddenNeuronsTextbox.setText("");
        }
    }//GEN-LAST:event_hiddenNeuronsTextboxActionPerformed

    private void iterationsTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iterationsTextboxActionPerformed
        if(!NewProcessor.isInteger(iterationsTextbox.getText())){
            JOptionPane.showMessageDialog(null, "Number of iterations must be an integer.", "Error", JOptionPane.ERROR_MESSAGE);
            iterationsTextbox.setText("");
        }
    }//GEN-LAST:event_iterationsTextboxActionPerformed

    private void printMonitorCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printMonitorCheckboxActionPerformed

    }//GEN-LAST:event_printMonitorCheckboxActionPerformed

    private void imageCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageCheckboxActionPerformed

    }//GEN-LAST:event_imageCheckboxActionPerformed

    private void loadNetworkCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadNetworkCheckboxActionPerformed
        loadNetworkFilebox.setEnabled(loadNetworkCheckbox.isSelected());
        loadNetworkChooseButton.setEnabled(loadNetworkCheckbox.isSelected());
        loadNetworkOpenButton.setEnabled(loadNetworkCheckbox.isSelected());
    }//GEN-LAST:event_loadNetworkCheckboxActionPerformed

    private void loadNetworkOpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadNetworkOpenButtonActionPerformed
        File file = new File(loadNetworkFilebox.getText());

        //First check if Desktop is supported by Platform or not
        if(!Desktop.isDesktopSupported()){
            JOptionPane.showMessageDialog(null, "Desktop is not supported - file cannot be opened", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Desktop desktop = Desktop.getDesktop();
            if (file.exists()) {
                try {
                    desktop.open(file);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            } else {
                JOptionPane.showMessageDialog(null, "File does not exist", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_loadNetworkOpenButtonActionPerformed

    private void loadNetworkFileboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadNetworkFileboxActionPerformed

    }//GEN-LAST:event_loadNetworkFileboxActionPerformed

    private void saveNetworkCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveNetworkCheckboxActionPerformed
        saveNetworkFilebox.setEnabled(saveNetworkCheckbox.isSelected());
        saveNetworkChooseButton.setEnabled(saveNetworkCheckbox.isSelected());
        saveNetworkOpenButton.setEnabled(saveNetworkCheckbox.isSelected());
    }//GEN-LAST:event_saveNetworkCheckboxActionPerformed

    private void saveNetworkOpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveNetworkOpenButtonActionPerformed
        File file = new File(saveNetworkFilebox.getText());

        //First check if Desktop is supported by Platform or not
        if(!Desktop.isDesktopSupported()){
            JOptionPane.showMessageDialog(null, "Desktop is not supported - file cannot be opened", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Desktop desktop = Desktop.getDesktop();
            if (file.exists()) {
                try {
                    desktop.open(file);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            } else {
                JOptionPane.showMessageDialog(null, "File does not exist", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_saveNetworkOpenButtonActionPerformed

    private void saveNetworkFileboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveNetworkFileboxActionPerformed

    }//GEN-LAST:event_saveNetworkFileboxActionPerformed

    private void saveReportCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveReportCheckboxActionPerformed
        saveReportFilebox.setEnabled(saveReportCheckbox.isSelected());
        saveReportChooseButton.setEnabled(saveReportCheckbox.isSelected());
        saveReportOpenButton.setEnabled(saveReportCheckbox.isSelected());
    }//GEN-LAST:event_saveReportCheckboxActionPerformed

    private void saveReportOpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveReportOpenButtonActionPerformed
        File file = new File(saveReportFilebox.getText());

        //First check if Desktop is supported by Platform or not
        if(!Desktop.isDesktopSupported()){
            JOptionPane.showMessageDialog(null, "Desktop is not supported - file cannot be opened", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Desktop desktop = Desktop.getDesktop();
            if (file.exists()) {
                try {
                    desktop.open(file);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            } else {
                JOptionPane.showMessageDialog(null, "File does not exist", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_saveReportOpenButtonActionPerformed

    private void saveReportFileboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveReportFileboxActionPerformed

    }//GEN-LAST:event_saveReportFileboxActionPerformed

    private void outputNamesOpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputNamesOpenButtonActionPerformed
        File file = new File(outputNamesFilebox.getText());

        //First check if Desktop is supported by Platform or not
        if(!Desktop.isDesktopSupported()){
            JOptionPane.showMessageDialog(null, "Desktop is not supported - file cannot be opened", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Desktop desktop = Desktop.getDesktop();
            if (file.exists()) {
                try {
                    desktop.open(file);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            } else {
                JOptionPane.showMessageDialog(null, "File does not exist", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_outputNamesOpenButtonActionPerformed

    private void outputNamesFileboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputNamesFileboxActionPerformed

    }//GEN-LAST:event_outputNamesFileboxActionPerformed

    private void inputsOpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputsOpenButtonActionPerformed
        File file = new File(inputsFilebox.getText());

        //First check if Desktop is supported by Platform or not
        if(!Desktop.isDesktopSupported()){
            JOptionPane.showMessageDialog(null, "Desktop is not supported - file cannot be opened", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Desktop desktop = Desktop.getDesktop();
            if (file.exists()) {
                try {
                    desktop.open(file);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            } else {
                JOptionPane.showMessageDialog(null, "File does not exist", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_inputsOpenButtonActionPerformed

    private void inputsFileboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputsFileboxActionPerformed

    }//GEN-LAST:event_inputsFileboxActionPerformed

    private void outputsOpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputsOpenButtonActionPerformed
        File file = new File(outputsFilebox.getText());

        //First check if Desktop is supported by Platform or not
        if(!Desktop.isDesktopSupported()){
            JOptionPane.showMessageDialog(null, "Desktop is not supported - file cannot be opened", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Desktop desktop = Desktop.getDesktop();
            if (file.exists()) {
                try {
                    desktop.open(file);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            } else {
                JOptionPane.showMessageDialog(null, "File does not exist", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_outputsOpenButtonActionPerformed

    private void outputsFileboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputsFileboxActionPerformed

    }//GEN-LAST:event_outputsFileboxActionPerformed

    private void dynamicRateCheckbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dynamicRateCheckbox1ActionPerformed
        iterationRadio.setEnabled(dynamicRateCheckbox1.isSelected());
        accuracyRadio.setEnabled(dynamicRateCheckbox1.isSelected());
        linearRadio.setEnabled(dynamicRateCheckbox1.isSelected());
        quadraticRadio.setEnabled(dynamicRateCheckbox1.isSelected());

    }//GEN-LAST:event_dynamicRateCheckbox1ActionPerformed

    private void customTypeRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customTypeRadioActionPerformed
        outputNamesFilebox.setEnabled(customTypeRadio.isSelected());
        outputNamesChooseButton.setEnabled(customTypeRadio.isSelected());
        outputNamesOpenButton.setEnabled(customTypeRadio.isSelected());
    }//GEN-LAST:event_customTypeRadioActionPerformed

    private void numbersNameTypeRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numbersNameTypeRadioActionPerformed
        outputNamesFilebox.setEnabled(customTypeRadio.isSelected());
        outputNamesChooseButton.setEnabled(customTypeRadio.isSelected());
        outputNamesOpenButton.setEnabled(customTypeRadio.isSelected());
    }//GEN-LAST:event_numbersNameTypeRadioActionPerformed

    private void lettersNameTypeRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lettersNameTypeRadioActionPerformed
        outputNamesFilebox.setEnabled(customTypeRadio.isSelected());
        outputNamesChooseButton.setEnabled(customTypeRadio.isSelected());
        outputNamesOpenButton.setEnabled(customTypeRadio.isSelected());
    }//GEN-LAST:event_lettersNameTypeRadioActionPerformed


    private void inputsChooseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputsChooseButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        String filename = file.getAbsolutePath().replace("\\", "/");
        inputsFilebox.setText(filename);
    }//GEN-LAST:event_inputsChooseButtonActionPerformed

    private void outputsChooseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputsChooseButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        String filename = file.getAbsolutePath().replace("\\", "/");
        outputsFilebox.setText(filename);
    }//GEN-LAST:event_outputsChooseButtonActionPerformed

    private void saveReportChooseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveReportChooseButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        String filename = file.getAbsolutePath().replace("\\", "/");
        saveReportFilebox.setText(filename);
    }//GEN-LAST:event_saveReportChooseButtonActionPerformed

    private void saveNetworkChooseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveNetworkChooseButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        String filename = file.getAbsolutePath().replace("\\", "/");
        saveNetworkFilebox.setText(filename);
    }//GEN-LAST:event_saveNetworkChooseButtonActionPerformed

    private void loadNetworkChooseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadNetworkChooseButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        String filename = file.getAbsolutePath().replace("\\", "/");
        loadNetworkFilebox.setText(filename);
    }//GEN-LAST:event_loadNetworkChooseButtonActionPerformed

    private void outputNamesChooseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputNamesChooseButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        String filename = file.getAbsolutePath().replace("\\", "/");
        outputNamesFilebox.setText(filename);
    }//GEN-LAST:event_outputNamesChooseButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        //TODO: Add code to reject invalid filenames
        Main.setInputsFilename(inputsFilebox.getText());
        Main.setOutputsFilename(outputsFilebox.getText());
        Main.setSaveReport(saveReportCheckbox.isSelected());
        Main.setReportFilename(saveReportFilebox.getText());
        Main.setSaveState(saveNetworkCheckbox.isSelected());
        Main.setSaveNetworkFilename(saveNetworkFilebox.getText());
        Main.setLoadState(loadNetworkCheckbox.isSelected());
        Main.setLoadNetworkFilename(loadNetworkFilebox.getText());
        Main.setNumberOfHiddens(NewProcessor.convertToInteger(hiddenNeuronsTextbox.getText()));
        Main.setIterations(NewProcessor.convertToInteger(iterationsTextbox.getText()));
        Main.setPrintMonitor(printMonitorCheckbox.isSelected());
        Main.setCreatePicture(imageCheckbox.isSelected());
        Main.setLearningRate(NewProcessor.convertToDouble(learningRateTextbox.getText()));
        if(dynamicRateCheckbox1.isSelected()){
            if(iterationRadio.isSelected()){
                if(linearRadio.isSelected()){
                    Main.setDynamicType(Main.ITERATION_LINEAR);
                } else {
                    Main.setDynamicType(Main.ITERATION_QUADRATIC);
                }
            } else {
                if(linearRadio.isSelected()){
                    Main.setDynamicType(Main.ACCURACY_LINEAR);
                } else {
                    Main.setDynamicType(Main.ACCURACY_QUADRATIC);
                }
            }
        } else {
            Main.setDynamicType(Main.CONSTANT);
        }

        if(numbersNameTypeRadio.isSelected()){
            Main.setOutputNamesType(Main.NUMBERS_NAMES);
        } else if(lettersNameTypeRadio.isSelected()){
            Main.setOutputNamesType(Main.LETTERS_NAMES);
        } else if(customTypeRadio.isSelected()){
            Main.setOutputNamesType(Main.USER_NAMES);
            Main.setUserNamesFilename(outputNamesFilebox.getText());
        }





        Main.startProgram();
    }//GEN-LAST:event_startButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(2);
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton accuracyRadio;
    private javax.swing.JToggleButton backButton;
    private javax.swing.ButtonGroup basisGroup;
    private javax.swing.JRadioButton customTypeRadio;
    private javax.swing.JCheckBox dynamicRateCheckbox1;
    private javax.swing.JToggleButton exitButton;
    private javax.swing.JTextField hiddenNeuronsTextbox;
    private javax.swing.JCheckBox imageCheckbox;
    private javax.swing.JButton inputsChooseButton;
    private javax.swing.JTextField inputsFilebox;
    private javax.swing.JButton inputsOpenButton;
    private javax.swing.JRadioButton iterationRadio;
    private javax.swing.JTextField iterationsTextbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField learningRateTextbox;
    private javax.swing.JRadioButton lettersNameTypeRadio;
    private javax.swing.JRadioButton linearRadio;
    private javax.swing.JCheckBox loadNetworkCheckbox;
    private javax.swing.JButton loadNetworkChooseButton;
    private javax.swing.JTextField loadNetworkFilebox;
    private javax.swing.JButton loadNetworkOpenButton;
    private javax.swing.ButtonGroup namesGroup;
    private javax.swing.JPanel networkSection;
    private javax.swing.JRadioButton numbersNameTypeRadio;
    private javax.swing.JButton outputNamesChooseButton;
    private javax.swing.JTextField outputNamesFilebox;
    private javax.swing.JButton outputNamesOpenButton;
    private javax.swing.JButton outputsChooseButton;
    private javax.swing.JTextField outputsFilebox;
    private javax.swing.JButton outputsOpenButton;
    private javax.swing.JCheckBox printMonitorCheckbox;
    private javax.swing.JRadioButton quadraticRadio;
    private javax.swing.ButtonGroup regressionGroup;
    private javax.swing.JCheckBox saveNetworkCheckbox;
    private javax.swing.JButton saveNetworkChooseButton;
    private javax.swing.JTextField saveNetworkFilebox;
    private javax.swing.JButton saveNetworkOpenButton;
    private javax.swing.JCheckBox saveReportCheckbox;
    private javax.swing.JButton saveReportChooseButton;
    private javax.swing.JTextField saveReportFilebox;
    private javax.swing.JButton saveReportOpenButton;
    private javax.swing.JLabel settingsTitle;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
